name: Profile Schemas CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: KirillBaranov/kb-labs-devkit/.github/actions/setup-node-pnpm@main
        with:
          node-version: '20'

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Build & Validate (schemas)
        run: pnpm -s profiles:ci

      - name: Upload dist (optional)
        uses: actions/upload-artifact@v4
        with:
          name: schemas-dist
          path: packages/profile-schemas/dist/
          if-no-files-found: ignore